# Generated by Django 3.0.7 on 2020-07-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='insh',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='length',
        ),
    ]
