# Generated by Django 3.0.7 on 2020-07-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
        ('menu_app', '0002_auto_20200627_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='category_app.Category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='menu_app.Menu')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
    ]
